# Site settings
title: HOME
tagline: Personal Blog
email: preetika.nith@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://preetikachandel.github.io" # the base hostname & protocol for your site
twitter_username: preetika
github_username:  PreetikaChandel




# Build settings
markdown: kramdown
